In [1]:
import pandas as pd

In [3]:
df_match = pd.read_csv('df_match.csv')
df_merged = pd.read_csv('df_merged.csv')
match_result = pd.read_csv('match_results.csv')

In [4]:
df_match

,team_id,match_result,user_name,season_grade,guild_name,kill,death,headshot,damage,assist,match_id,match_type,match_mode,match_map,date_match,is_win,is_draw,is_loss
0,1,2,자다,특급준장,cynosure,10,12,0,1572.0,4,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,0,0,1
1,1,2,도리,특급대장,마뇽,9,13,0,1808.0,1,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,0,0,1
2,0,1,rxvx,특급대장,UlsaN_CIaN,21,8,1,3744.0,0,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,1,0,0
3,1,2,킥,특급대장,lunatic`Gaming,20,13,6,3599.0,7,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,0,0,1
4,1,2,T1,부사령관,활력,9,13,0,1763.0,0,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,0,0,1
5,1,2,도독이,특급대장,도독이들,12,13,2,1496.0,5,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,0,0,1
6,1,2,YAR`',특급대장,ΗΑΕ,1,1,0,158.0,0,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,0,0,1
7,0,1,임메리,특급대장,명왕,12,15,4,2217.0,5,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,1,0,0
8,0,1,ㅈㅋㅋㅋ,특공중령 5호봉,ː대구광역시ː,5,12,1,849.0,4,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,1,0,0
9,0,1,(♡'v'♡),특급중장,마라탕후룩,6,13,2,994.0,8,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,1,0,0
10,0,1,ㅇㄴS2,특급대장,NaN,14,9,2,2660.0,7,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,1,0,0
11,0,1,정재엽,특급대장,Finger,20,7,1,4579.0,0,250718062509119001,퀵매치 클랜전,폭파미션,프로방스,2025-07-17T21:25:09.338Z,1,0,0

In [5]:
match_result

   user_name  match_result            match_id  team_id
0         자다             0  250718062509119001        1
1         도리             0  250718062509119001        1
2       rxvx             1  250718062509119001        0
3          킥             0  250718062509119001        1
4         T1             0  250718062509119001        1
5        도독이             0  250718062509119001        1
6      YAR`'             0  250718062509119001        1
7        임메리             1  250718062509119001        0
8       ㅈㅋㅋㅋ             1  250718062509119001        0
9    (♡'v'♡)             1  250718062509119001        0
10      ㅇㄴS2             1  250718062509119001        0
11       정재엽             1  250718062509119001        0

In [6]:
df_merged

,user_name,grade_ranking,season_grade_ranking,recent_win_rate,recent_kill_death_rate,recent_assault_rate,recent_sniper_rate,recent_special_rate,solo_rank_match_score,party_rank_match_score
0,아리,21,3110,100.000000,56.833332,51.666664,50.000000,51.000000,2721,2400
1,(♡'v'♡),232536,94348,50.000000,40.833332,39.000000,50.333332,32.000000,1545,1874
2,T1,6422,926,50.000000,53.846157,0.000000,67.346939,0.000000,2897,3050
3,ㅇㄴS2,65518,46042,85.000000,50.833332,47.666664,57.627117,71.875000,1600,2077
4,도독이,26914,54316,43.333332,43.833332,36.333332,47.666668,44.333332,2516,3667
5,도리,238564,66508,41.666664,44.333332,42.666668,55.666668,48.000000,2250,2570
6,자다,612323,167853,53.333336,46.333332,46.333332,61.000000,51.612904,2403,2109
7,정재엽,10953,5937,58.695648,47.000000,30.769232,54.140129,59.183674,2599,2637
8,킥,21918,64949,50.000000,49.333336,51.666668,59.000000,47.000000,3266,2400